### ISSUE TITLE
Gerätewechsel - Download Literatur

### ISSUE THREAD

**Issue by Peter-66** [AntonyCorbett/JWLMerge#22]
Gibt es die Möglichkeit bei einem Gerätewechsel sich den umständlichen Download aller Bücher, Broschüren usw. zu sparen?

Kann man ein bestimmtes Verzeichnis kopieren und JW Library erkennt es und installiert damit auromatisch die bereits installierte Literatur?

Hat jemand schon mal Erfahrungen damit gemacht?

Aktuell mal geht es um ein Windows Gerät. Vielleicht wäre es auch interessant für ein Android oder Apple.

Vielen Dank vorab.

Peter

**Comment by AntonyCorbett** [comment]
@Peter-66 you ask about the possibility of populating JWL with publications when you change device. Since publications are stored internally in database tables rather than files, it's never simply a case of copying files into a folder. The job can be done but it involves writing directly to the JWL database which is probably outside of the terms and conditions of use.
