### ISSUE TITLE
Export notes by publication

### ISSUE THREAD

**Issue by aemb77** [AntonyCorbett/JWLMerge#70]
Hello. Is it possible to make a new feature?

I need to export some notes by publications, not only the Bible notes. For eg. I want to transfer my personal notes in my book LFF to another brother, not ALL my notes. Is it possible?

Thanks a lot.

**Comment by knardbb** [comment]
Hi...

I'm very interested by this request... I explain you why it would be very useful...
I'm a CO in foreign languages. That means I have to conduct the pioneer school in different languages.
My problem is once I've prepared the pt14's book (pioneer book) in one language, all my notes in this language will appear whatever the language in which I open the book... Normally it's useful but not in my case....

So if I could extract the notes just for this book I could have them according to the language I use....

**Comment by AntonyCorbett** [comment]
@knardbb User highlighting is per-language (for obvious reasons) but user notes are not (as you've discovered). So I can independently highlight different lines of text in the different language versions of a book (as I would expect), but my notes appear in all language editions regardless of which one I used when making the note. As you suggest, this is probably by design as most users would want it to work this way. Interestingly, it is possible to programmatically determine the language of the book in which the note was originally made, so if you have been consistent in your entering notes then it should be possible to distinguish one language from another. One option may be a function to remove notes by language.

Perhaps you can describe exactly what you're aiming to achieve? Is it to extract notes into another format or to have JWL backups that contain notes in each language, or something else?

**Comment by knardbb** [comment]
Sorry for my late answer....
In fact my question is not relevant anymore for me since I receive a new
assignment starting September. I will not be in foreign field anymore. So I
will conduct pioneer school only in one language...

Anyway. Th e problem was that my notes for the book of pioneer are not in a
specific language. They can be in my language, french, but in a book in
another language... For exemple, haitian creole.
The problem is, when you open the book in French, you see all the notes you
have for the other language, haitian. Usually it's very good, very useful.
But in this particular case, it's not... Because in one page, you can have
several notes... and you can't find where you are when the notes were for
another language. The questions are not all the sames... and things become
very confusing.....

So I was wondering if there was a way to export the notes of one specific
book.

But, no need anymore ;-)
Thanks.
Seb

Le lun. 28 mars 2022 à 19:42, Antony Corbett ***@***.***> a
écrit :
