### ISSUE TITLE
Merge Issue 15-7-23 v 2.1.0.5

### ISSUE THREAD

**Issue by nandpwalk** [AntonyCorbett/JWLMerge#99]
**Describe the bug**
When merging I now get "Wrong database version found (13) in filename.jwlibrary. Expecting 8

**To Reproduce**
Tried to merge two backups as normal.

**Expected behavior**
A successful merge!

**Screenshots**
see attached.

![Screenshot 2023-07-17 173932](https://github.com/AntonyCorbett/JWLMerge/assets/139795492/bcf3d6a0-7e6f-4804-9d9b-e8ac797566d0)

**Desktop (please complete the following information):**
Win 10
Jw library v14.0.138 and have just downloaded the latest jwl merge v 2.1.0.5 uploaded two days ago.

**Comment by dl9abl** [comment]
Hello Anthony, David and Henry.

Thank you for your tool, which is essential for me. It is nice to have a playlist in the JW app now, however it is more important for me to sychronize my studynotes and other with all my devices.
 
One of my best friends is the overseer of an RTO. He always gets the beta versions of the JW app. So he also has the opportunity to submit suggestions for improvements. We spent the day together yesterday. Told him about the dilemma with JWmerge. He will use the above opportunity this week to write a note to the appropriate department.

I'll take the liberty of a small hint: did you receive a negative response to your January 2023 request to Bethel, or no response at all? If the case is the latter, then it may make sense to repeat your January request to Bethel, because almost all of Bethel's departments cannot complain about a lack of work. As a result, some questions may unfortunately fall by the wayside.

Thanks to you again for six years of excellent work! Have a nice day2day!

**Comment by tdubu** [comment]
My wife and I appreciated your app so much, it made our lives so much easier and we always had all our notes with us no matter which device we were on. Maybe one day we'll get access to this tool again in one form or another. Until then, we'll just have to "exercise patience" and do a lot of copying and pasting!

**Comment by Riroux13** [comment]
![Capture d'écran 2023-07-19 114714](https://github.com/AntonyCorbett/JWLMerge/assets/98409141/27f28bb3-b12e-457f-8c11-be61622879a9) bonjours, depuis la mise à jour 2.1.0.5 j'ai également ce problème. je suis sous windows 11. Merci pour ton super logiciel qui est super pratique pour faire des sauvegardes.

**Comment by AntonyCorbett** [comment]
@Riroux13 Note that this project is no longer compatible with the latest version of the JW Library. In July 2023 the database schema was changed from v8 to v13 and I will not be updating JWLMerge to support the new version. In Jan 2023, the JW Library licence agreement was strengthened, but it also gave opportunity for 3rd party developers to apply for official permission to do the sort of work that is present in JWLMerge. I made an application in January but have not received permission, and in these circumstances feel it best to archive the project at this juncture. Thank you for your understanding, and for your valuable input and feedback on the project over the last 6 years.

**Comment by Riroux13** [comment]
Thank you

 

De : Antony Corbett ***@***.***> 
Envoyé : jeudi 20 juillet 2023 00:37
À : AntonyCorbett/JWLMerge ***@***.***>
Cc : Riroux13 ***@***.***>; Mention ***@***.***>
Objet : Re: [AntonyCorbett/JWLMerge] Merge Issue 15-7-23 v 2.1.0.5 (Issue #99)

 

@Riroux13 <https://github.com/Riroux13>  Note that this project is no longer compatible with the latest version of the JW Library. In July 2023 the database schema was changed from v8 to v13 and I will not be updating JWLMerge to support the new version. In Jan 2023, the JW Library licence agreement was strengthened, but it also gave opportunity for 3rd party developers to apply for official permission to do the sort of work that is present in JWLMerge. I made an application in January but have not received permission, and in these circumstances feel it best to archive the project at this juncture. Thank you for your understanding, and for your valuable input and feedback on the project over the last 6 years.

**Comment by AntonyCorbett** [comment]
@dl9abl I sent email on 15 Jan to the address given in the revised terms, however I received no response. I thought that I would give it 6 months and then take a view on it. At this point I must conclude that permission is not given. Thanks for your interest in the project. Best wishes, Antony
